FROM golang:1.21-alpine3.18

ARG USERNAME=go
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create the user
RUN addgroup -S ${USER_GID} && adduser -S ${USERNAME} -G ${USER_GID}

RUN apk --no-cache add libaio libnsl libc6-compat curl bash openjdk8-jre

ENV MAVEN_VERSION 3.5.4
ENV MAVEN_HOME /usr/lib/mvn
ENV PATH $MAVEN_HOME/bin:$PATH

RUN wget http://archive.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz && \
  tar -zxvf apache-maven-$MAVEN_VERSION-bin.tar.gz && \
  rm apache-maven-$MAVEN_VERSION-bin.tar.gz && \
  mv apache-maven-$MAVEN_VERSION /usr/lib/mvn