FROM golang:1.21-alpine3.18

ARG USERNAME=go
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create the user
RUN addgroup -S ${USER_GID} && adduser -S ${USERNAME} -G ${USER_GID}

RUN apk --no-cache add libaio libnsl libc6-compat curl bash openjdk8-jre && \
    cd /tmp && \
    curl -o instantclient-basiclite.zip https://download.oracle.com/otn_software/linux/instantclient/instantclient-basiclite-linuxx64.zip -SL && \
    unzip instantclient-basiclite.zip && \
    mv instantclient*/ /usr/lib/instantclient && \
    rm instantclient-basiclite.zip && \
    ln -s /usr/lib/instantclient/libclntsh.so.19.1 /usr/lib/libclntsh.so && \
    ln -s /usr/lib/instantclient/libocci.so.19.1 /usr/lib/libocci.so && \
    ln -s /usr/lib/instantclient/libociicus.so /usr/lib/libociicus.so && \
    ln -s /usr/lib/instantclient/libnnz19.so /usr/lib/libnnz19.so && \
    ln -s /usr/lib/libnsl.so.2 /usr/lib/libnsl.so.1 && \
    ln -s /lib/libc.so.6 /usr/lib/libresolv.so.2 && \
    ln -s /lib64/ld-linux-x86-64.so.2 /usr/lib/ld-linux-x86-64.so.2

RUN rm -rf /usr/lib/jvm/java-17-openjdk/*src.zip \
    /usr/lib/jvm/java-17-openjdk/lib/missioncontrol \
    /usr/lib/jvm/java-17-openjdk/lib/visualvm \
    /usr/lib/jvm/java-17-openjdk/lib/*javafx* \
    /usr/lib/jvm/java-17-openjdk/jre/plugin \
    /usr/lib/jvm/java-17-openjdk/jre/bin/javaws \
    /usr/lib/jvm/java-17-openjdk/jre/bin/jjs \
    /usr/lib/jvm/java-17-openjdk/jre/bin/orbd \
    /usr/lib/jvm/java-17-openjdk/jre/bin/pack200 \
    /usr/lib/jvm/java-17-openjdk/jre/bin/policytool \
    /usr/lib/jvm/java-17-openjdk/jre/bin/rmid \
    /usr/lib/jvm/java-17-openjdk/jre/bin/rmiregistry \
    /usr/lib/jvm/java-17-openjdk/jre/bin/servertool \
    /usr/lib/jvm/java-17-openjdk/jre/bin/tnameserv \
    /usr/lib/jvm/java-17-openjdk/jre/bin/unpack200 \
    /usr/lib/jvm/java-17-openjdk/jre/lib/javaws.jar \
    /usr/lib/jvm/java-17-openjdk/jre/lib/deploy* \
    /usr/lib/jvm/java-17-openjdk/jre/lib/desktop \
    /usr/lib/jvm/java-17-openjdk/jre/lib/*javafx* \
    /usr/lib/jvm/java-17-openjdk/jre/lib/*jfx* \
    /usr/lib/jvm/java-17-openjdk/jre/lib/amd64/libdecora_sse.so \
    /usr/lib/jvm/java-17-openjdk/jre/lib/amd64/libprism_*.so \
    /usr/lib/jvm/java-17-openjdk/jre/lib/amd64/libfxplugins.so \
    /usr/lib/jvm/java-17-openjdk/jre/lib/amd64/libglass.so \
    /usr/lib/jvm/java-17-openjdk/jre/lib/amd64/libgstreamer-lite.so \
    /usr/lib/jvm/java-17-openjdk/jre/lib/amd64/libjavafx*.so \
    /usr/lib/jvm/java-17-openjdk/jre/lib/amd64/libjfx*.so \
    /usr/lib/jvm/java-17-openjdk/jre/lib/ext/jfxrt.jar \
    /usr/lib/jvm/java-17-openjdk/jre/lib/ext/nashorn.jar \
    /usr/lib/jvm/java-17-openjdk/jre/lib/oblique-fonts \
    /usr/lib/jvm/java-17-openjdk/jre/lib/plugin.jar \
    /tmp/* /var/cache/apk/*

ENV ORACLE_BASE /usr/lib/instantclient
ENV LD_LIBRARY_PATH /usr/lib/instantclient
ENV TNS_ADMIN /usr/lib/instantclient
ENV ORACLE_HOME /usr/lib/instantclient


ENV MAVEN_VERSION 3.5.4
ENV MAVEN_HOME /usr/lib/mvn
ENV PATH $MAVEN_HOME/bin:$PATH

RUN wget http://archive.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz && \
  tar -zxvf apache-maven-$MAVEN_VERSION-bin.tar.gz && \
  rm apache-maven-$MAVEN_VERSION-bin.tar.gz && \
  mv apache-maven-$MAVEN_VERSION /usr/lib/mvn